services:
  otel-collector:
    image: otel/opentelemetry-collector:0.104.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./infra/observability/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4318:4318"  # OTLP http
    depends_on: []

  tempo:
    image: grafana/tempo:2.5.0
    ports:
      - "3200:3200"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./infra/observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - tempo
